"""
Profile every CSV in data/raw/ and write a markdown report to docs/data_profile.md.

Run as the first step of the pipeline. Lets you understand row counts, dtypes,
null patterns, and the '\\N' marker before designing schemas for BigQuery.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

import config


def profile_csv(path: Path) -> dict:
    """Read a CSV and return profile metadata."""
    # Ergast CSVs use '\N' (literal backslash-N) as their null marker
    df = pd.read_csv(path, na_values=["\\N"], keep_default_na=True, low_memory=False)

    return {
        "filename": path.name,
        "rows": len(df),
        "columns": len(df.columns),
        "column_info": [
            {
                "name": col,
                "dtype": str(df[col].dtype),
                "nulls": int(df[col].isna().sum()),
                "null_pct": round(df[col].isna().mean() * 100, 1),
                "sample": _safe_sample(df[col]),
            }
            for col in df.columns
        ],
    }


def _safe_sample(series: pd.Series) -> str:
    """Return a short, printable sample value for the column."""
    non_null = series.dropna()
    if non_null.empty:
        return ""
    val = str(non_null.iloc[0])
    return val if len(val) <= 30 else val[:27] + "..."


def render_markdown(profiles: list[dict]) -> str:
    """Render profile data as a markdown document."""
    lines: list[str] = [
        "# F1 Dataset Profile",
        "",
        "Auto-generated by `scripts/profile_data.py`. Do not edit by hand.",
        "",
        f"**Source files:** {len(profiles)} CSVs from `data/raw/`",
        f"**Total rows across all files:** {sum(p['rows'] for p in profiles):,}",
        "",
        "---",
        "",
    ]

    for p in profiles:
        lines.append(f"## `{p['filename']}`")
        lines.append("")
        lines.append(f"- **Rows:** {p['rows']:,}")
        lines.append(f"- **Columns:** {p['columns']}")
        lines.append("")
        lines.append("| Column | Dtype | Nulls | Null % | Sample |")
        lines.append("|---|---|---|---|---|")
        for col in p["column_info"]:
            sample = col["sample"].replace("|", "\\|")
            lines.append(
                f"| `{col['name']}` | {col['dtype']} | "
                f"{col['nulls']:,} | {col['null_pct']}% | {sample} |"
            )
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    csv_files = sorted(config.DATA_RAW_DIR.glob("*.csv"))

    if not csv_files:
        sys.exit(
            f"ERROR: no CSV files found in {config.DATA_RAW_DIR}\n"
            f"Run `make download` first."
        )

    print(f"Profiling {len(csv_files)} CSV files from {config.DATA_RAW_DIR}...")
    profiles = []
    for path in csv_files:
        print(f"  - {path.name}")
        profiles.append(profile_csv(path))

    config.DOCS_DIR.mkdir(parents=True, exist_ok=True)
    output_path = config.DOCS_DIR / "data_profile.md"
    output_path.write_text(render_markdown(profiles))

    total_rows = sum(p["rows"] for p in profiles)
    print(f"\nDone. {len(profiles)} files, {total_rows:,} total rows.")
    print(f"Report written to {output_path}")


if __name__ == "__main__":
    main()
